# Generated by Django 5.2.7 on 2025-10-29 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_time",
                    models.DateTimeField(
                        help_text="Patient requested appointment time"
                    ),
                ),
                (
                    "confirmed_time",
                    models.DateTimeField(
                        blank=True, help_text="Hospital confirmed time", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for appointment"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes from hospital/doctor"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hospital user who assigned the doctor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Doctor assigned by hospital",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="hospitals.hospitaldoctorprofile",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="hospitals.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "PATIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "appointments",
                "ordering": ["-requested_time"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"],
                        name="appointment_patient_6fe260_idx",
                    ),
                    models.Index(
                        fields=["hospital", "status"],
                        name="appointment_hospita_ab3622_idx",
                    ),
                    models.Index(
                        fields=["assigned_doctor", "status"],
                        name="appointment_assigne_37159e_idx",
                    ),
                    models.Index(
                        fields=["requested_time"], name="appointment_request_729b84_idx"
                    ),
                ],
            },
        ),
    ]
