# Generated by Django 5.2.7 on 2025-10-29 18:41

import django.core.validators
import django.db.models.deletion
import records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField(help_text="Diagnosis details")),
                (
                    "investigations",
                    models.TextField(
                        blank=True, help_text="Recommended investigations/tests"
                    ),
                ),
                (
                    "treatment_plan",
                    models.TextField(
                        blank=True, help_text="Treatment plan and recommendations"
                    ),
                ),
                (
                    "medicines",
                    models.JSONField(
                        default=list,
                        help_text="List of medicines with dosage, frequency, duration",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, help_text="Recommended follow-up date", null=True
                    ),
                ),
                (
                    "referral_notes",
                    models.TextField(
                        blank=True, help_text="Referral to specialist if needed"
                    ),
                ),
                (
                    "doctor_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes from doctor"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Prescription version number"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related appointment if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="hospitals.hospitaldoctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "PATIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="records.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "db_table": "prescriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="prescription_attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="records.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Attachment",
                "verbose_name_plural": "Prescription Attachments",
                "db_table": "prescription_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=records.models.patient_report_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("LAB", "Lab Report"),
                            ("PRESCRIPTION", "Prescription"),
                            ("XRAY", "X-Ray"),
                            ("MRI", "MRI Scan"),
                            ("CT", "CT Scan"),
                            ("ULTRASOUND", "Ultrasound"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("title", models.CharField(help_text="Report title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Report description"),
                ),
                (
                    "report_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the medical report/test",
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hospital where report was generated (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_reports",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "PATIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Report",
                "verbose_name_plural": "Patient Reports",
                "db_table": "patient_reports",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "uploaded_at"],
                        name="patient_rep_patient_f93693_idx",
                    ),
                    models.Index(
                        fields=["file_type"], name="patient_rep_file_ty_ce3e88_idx"
                    ),
                    models.Index(
                        fields=["hospital"], name="patient_rep_hospita_0df3ec_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "created_at"], name="prescriptio_patient_50dfd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["doctor", "created_at"], name="prescriptio_doctor__2c554b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["appointment"], name="prescriptio_appoint_6d01d6_idx"
            ),
        ),
    ]
