# Generated by Django 5.2.7 on 2025-10-29 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=17)),
                ("address", models.TextField()),
                (
                    "location",
                    models.TextField(help_text="Detailed location/area description"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "ADMIN"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_hospitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "HOSPITAL"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospital",
                "verbose_name_plural": "Hospitals",
                "db_table": "hospitals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
                "ordering": ["hospital", "name"],
            },
        ),
        migrations.CreateModel(
            name="HospitalDoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnic", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("license_number", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=17)),
                (
                    "available_timings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object with day: [time_slots] mapping",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_doctor_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profiles",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospital Doctor Profile",
                "verbose_name_plural": "Hospital Doctor Profiles",
                "db_table": "hospital_doctor_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(
                fields=["is_approved", "created_at"],
                name="hospitals_is_appr_b17ec0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(
                fields=["license_number"], name="hospitals_license_30c37d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(
                fields=["latitude", "longitude"], name="hospitals_latitud_0ad327_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["hospital", "name"], name="departments_hospita_d56278_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("hospital", "name")},
        ),
        migrations.AddIndex(
            model_name="hospitaldoctorprofile",
            index=models.Index(
                fields=["hospital", "is_active"], name="hospital_do_hospita_0adce0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitaldoctorprofile",
            index=models.Index(
                fields=["user", "hospital"], name="hospital_do_user_id_3c5fd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitaldoctorprofile",
            index=models.Index(
                fields=["specialization"], name="hospital_do_special_74efcc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hospitaldoctorprofile",
            unique_together={("hospital", "user")},
        ),
    ]
