# Generated by Django 6.0 on 2026-01-02 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospitals.department'),
        ),
        migrations.AlterField(
            model_name='hospitaldoctorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
