# Generated by Django 5.2.7 on 2025-10-29 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=255)),
                (
                    "patient_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Patient age, allergies, comorbidities, etc.",
                    ),
                ),
                (
                    "alternatives",
                    models.JSONField(
                        default=list, help_text="List of alternative medicines"
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(
                        default=list, help_text="List of warnings and contraindications"
                    ),
                ),
                (
                    "suggestion",
                    models.TextField(blank=True, help_text="General suggestion"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="LLM response time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine Recommendation",
                "verbose_name_plural": "Medicine Recommendations",
                "db_table": "medicine_recommendations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["medicine_name", "created_at"],
                        name="medicine_re_medicin_1266a4_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "created_at"],
                        name="medicine_re_request_f562e3_idx",
                    ),
                ],
            },
        ),
    ]
